import { useEffect, useState } from 'react'
import { updateSettings } from '../services/settingsService'

export function WebsiteSettings({ settings, onSettingsChange }) {
  const [form, setForm] = useState(settings)
  const [state, setState] = useState({ loading: false, message: '', error: '' })
  useEffect(() => setForm(settings), [settings])
  const save = async (event) => { event.preventDefault(); setState({ loading: true, message: '', error: '' }); try { const next = await updateSettings(form); onSettingsChange(next); setState({ loading: false, message: 'Website settings saved.', error: '' }) } catch (error) { setState({ loading: false, message: '', error: error.message || 'Could not save settings.' }) } }
  return <div className="settings-page"><div className="page-heading"><div><span className="section-kicker">WEBSITE SETTINGS</span><h2>Public website settings</h2><p>Manage the public URLs and contact details used by Jenisha Online Service.</p></div></div><form className="settings-card" onSubmit={save}><div className="settings-card-head"><div><h3>General configuration</h3><p>Only URLs are stored here. Image files stay on Hostinger.</p></div><span className="firestore-note">Firestore · siteSettings/general</span></div><div className="settings-fields"><label>Logo URL<input type="url" value={form.logoUrl} onChange={(event) => setForm({ ...form, logoUrl: event.target.value })} placeholder="https://your-domain.com/website/logo/..." /></label><label>QR code URL<input type="url" value={form.qrCodeUrl} onChange={(event) => setForm({ ...form, qrCodeUrl: event.target.value })} placeholder="https://your-domain.com/website/qr-code/..." /></label><label>Google Play image URL<input type="url" value={form.googlePlayUrl} onChange={(event) => setForm({ ...form, googlePlayUrl: event.target.value })} placeholder="https://your-domain.com/website/google-play/..." /></label><label>WhatsApp number<input type="text" value={form.whatsappNumber} onChange={(event) => setForm({ ...form, whatsappNumber: event.target.value })} placeholder="919876543210" /></label></div>{state.message && <p className="status-message success">{state.message}</p>}{state.error && <p className="status-message error">{state.error}</p>}<div className="form-actions"><button className="primary-button" type="submit" disabled={state.loading}>{state.loading ? 'Saving...' : 'Save settings'}</button></div></form></div>
}
